-- V3__add_auto_increment_to_ids.sql
USE playvaultdb;

ALTER TABLE customers MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE payment_infos MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE publishers MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE categories MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE system_requirements MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE platforms MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE game_basic_infos MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE reviews MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE promotions MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE carts MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE cart_items MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE orders MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE order_items MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE invoices MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE payments MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE reports MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE block_records MODIFY id BIGINT AUTO_INCREMENT;
